config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "login#login"



  # path w url    kontroler# funkcja
  get 'home' => 'home#home'
  get 'login' => 'login#login'
  post 'login' => 'login#create'
  delete 'destroy' => 'login#destroy'
  get 'upload' => 'upload#upload'
  post 'submit' => 'upload#submit'
  get 'result' => 'upload#result'
  get "download_image" =>'shared#download'
  get 'history' =>'shared#history'
  get 'shared' => 'shared#shared'
  get 'myphotos' => 'shared#my_photos'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes 
    attribute:user
end

app/models/download.rb
class Download < ApplicationRecord
    belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :user
    has_one_attached :pic
    has_many :downloads, dependent: nil
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, format: {with: /\A[^@\s]+@[^@\s]+\z/, message: "to nie jest adres email"}
    validates :department, presence: true
    has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action:set_current_user
    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id:session[:user_id])
        end  
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def home
          
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
    def login

    end
    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to home_path
        else
            flash[:notice] = "Niepoprawny email lub hasło"
            redirect_to login_path
        end    
    end
    def destroy 
        session[:user_id]=nil
        redirect_to login_path, notice: "Wylogowano"
    end
    
end

app/controllers/shared_controller.rb
class SharedController < ApplicationController
    def shared
        @photos = Photo.joins("JOIN users ON users.id = photos.user_id AND users.department="+"'#{Current.user.department.to_s}' AND users.id != "+" '#{Current.user.id}'")
    end

    def my_photos
        @photos = Photo.where(user:Current.user)
    end

    def download
        @info =params[:id]
        @photo =Photo.find(params[:id]) #Photo.where(id:params[:id])
        @photo.downloads.create(by_who:Current.user.email, date:Time.now, )
    end

    def history
        @downloads =Download.where(photo_id:params[:id])
    end
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
    def upload

    end
    def submit 
        begin
            @photo = Current.user.photos.create(name:params[:name], data_dodania:Time.now, desc:params[:desc], pic: params[:pic])
            redirect_to result_path(:succes=>true) #method: :get, params:{succes:true}
        rescue =>e
            redirect_to result_path(:succes=>false)
        end
    end

    def result
        @result = params[:succes]
        @photos = Photo.where(user:Current.user)
        if @result=="true"
            flash[:notice] = "Dodawanie przebiegło pomyślnie"
        else
            flash[:notice] = "Błąd dodawania"
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/home/home.html.erb
<%= stylesheet_link_tag "style.css" %>
<div class="insideapp">
    <%= render partial: "navbar/navbar"%>
    <div class="maincontainer" >
        <%= button_to "DODAJĘ", upload_path, method: :get, class:"longbutton"%>
        <%= button_to "MOJE ZDJĘCIA", myphotos_path, method: :get, class:"longbutton"%>
        <%= button_to "UDOSTĘPNIONE MI", shared_path, method: :get, class:"longbutton"%>
    </div>
</div>    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotosExchange</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login/login.html.erb
<%= stylesheet_link_tag "style.css" %>
<div class="app">
<h1>SYSTEM WYMIANY ZDJĘĆ</h1>
<div class="maincontainer" >
    <%= flash[:notice] %>
    <%= form_with url: login_path do |form| %>
    <div class="logininputsgroup">
        <%= form.text_field :email, placeholder: "EMAIL"%>
        <%= form.password_field :password, placeholder: "HASŁO", style:"margin-bottom: 45px"%>
    </div>
    <%= form.submit "ZALOGUJ", class: "longbutton" %>
    <% end %>
</div>
</div>

app/views/navbar/_navbar.html.erb
<%= stylesheet_link_tag "navbar.css" %>
<nav>
    <h2>
        SYSTEM WYMIANY ZDJĘĆ
    </h2>
    <% if Current.user %>
    <div class="navcolumn">
        <%= button_to "WYLOGUJ", destroy_path, method: :delete %>
        <div class="logininfo">zalogowany jako: &nbsp; <span><%= Current.user.email %><span></div>
    </div>
   <% end %>
</nav>

app/views/shared/download.html.erb
<%= stylesheet_link_tag "style.css" %>
<div class="insideapp">
    <%= render partial: "navbar/navbar"%>
    <div class="maincontainer" >
        <div class="choosebranchheader">
            <p>Pobieranie:</p>
            <%= button_to shared_path, class:"backbutton",  method: :get do %>
                <i class="fa-solid fa-arrow-left"></i>
            <% end %>
        </div>
        <div class="photosgrip">
           <div class="downloadphoto">
                <% if @photo.pic.attached? %>
                    <image src="<%=(url_for(@photo.pic))%>">
                <% end %>
                <div class="photodesc">   
                    <h3><%=@photo.name%></h3>
                    <p><%=@photo.data_dodania.strftime("%d.%m.%Y - %H:%M:%S")%></p>
                    <p><%=@photo.desc%></p>
                    <%= link_to "Pobieram", url_for(@photo.pic), download: @photo.pic %>
                </div>
            </div> 
        </div>
    </div>
</div>    

app/views/shared/history.html.erb
<%= stylesheet_link_tag "style.css" %>
<div class="insideapp">
    <%= render partial: "navbar/navbar"%>
    <div class="maincontainer" >
        <div class="choosebranchheader">
            <p>Historia pobrań:</p>
            <%= button_to myphotos_path, class:"backbutton",  method: :get do %>
                <i class="fa-solid fa-arrow-left"></i>
            <% end %>
        </div>
        <div class="historygrip">
            <% @downloads.each do |download| %>
                    <div class="downloadcard">
                        <p style="color:#18A0DB"><strong><%=download.by_who%></strong></p>
                        <p><%=download.date.strftime("%d.%m.%Y - %H:%M:%S")%></p>
                    </div>
            <%end%>
        </div>
    </div>
</div>    

app/views/shared/my_photos.html.erb
<%= stylesheet_link_tag "style.css" %>
<div class="insideapp">
    <%= render partial: "navbar/navbar"%>
    <div class="maincontainer" >
        <div class="choosebranchheader">
            <p>Zdjęcia wgrane przez Ciebie:</p>
            <%= button_to home_path, class:"backbutton",  method: :get do %>
                <i class="fa-solid fa-arrow-left"></i>
            <% end %>
        </div>
        <div class="photosgrip">
            <% @photos.each do |photo| %>
                <div class="singlephotofromgrip">
                    <% if photo.pic.attached? %>
                        <image src="<%=(url_for(photo.pic))%>">
                    <% end %>   
                    <h3><%=photo.name%></h3>
                    <p><%=photo.data_dodania.strftime("%d.%m.%Y - %H:%M:%S")%></p>
                    <p><%=photo.desc%></p>
                    <%= button_to "Historia", history_path, class: "historybutton", method: :get, params:{id:photo.id} %>
                </div>
            <%end%>
        </div>
    </div>
</div>    

app/views/shared/shared.html.erb
<%= stylesheet_link_tag "style.css" %>
<div class="insideapp">
    <%= render partial: "navbar/navbar"%>
    <div class="maincontainer" >
        <div class="choosebranchheader">
            <p>Zdjęcia udostępnione dla Ciebie:</p>
            <%= button_to home_path, class:"backbutton",  method: :get do %>
                <i class="fa-solid fa-arrow-left"></i>
            <% end %>
        </div>
        <div class="photosgrip">
            <% @photos.each do |photo| %>
                <div class="singlephotofromgrip">
                    <% if photo.pic.attached? %>
                        <image src="<%=(url_for(photo.pic))%>">
                    <% end %>   
                    <h3><%=photo.name%></h3>
                    <p><%=photo.data_dodania.strftime("%d.%m.%Y - %H:%M:%S")%></p>
                    <p><%=photo.desc%></p>
                    <%= button_to "Pobierz",  download_image_path, class: "historybutton", method: :get, params:{id:photo.id} %>
                </div>
            <%end%>
        </div>
    </div>
</div>    

app/views/upload/result.html.erb
<%= stylesheet_link_tag "style.css" %>
<div class="insideapp">
    <%= render partial: "navbar/navbar"%>
    <div class="maincontainer" >
        <div class="uploadheader">
            <p>Dodawanie nowego zdjęcia:</p>
            <%= button_to home_path, class:"backbutton",  method: :get do %>
                <i class="fa-solid fa-arrow-left"></i>
            <% end %>
            
        </div>
        <div class="resultbody">
            <div><%= flash[:notice] %></div>
        </div>
        </div>
    </div>
</div> 

app/views/upload/upload.html.erb
<%= stylesheet_link_tag "style.css" %>
<div class="insideapp">
    <%= render partial: "navbar/navbar"%>
    <div class="maincontainer" >
        <div class="uploadheader">
            <p>Dodawanie nowego zdjęcia:</p>
            <%= button_to home_path, class:"backbutton",  method: :get do %>
                <i class="fa-solid fa-arrow-left"></i>
            <% end %>
            
        </div>
        <div class="uploadbody">
            <%= form_with url: submit_path,  class: "uploadform" do |f| %>
                <%=f.text_field :name, placeholder:"Nazwa"%>
                <%= f.file_field :pic%>
                <%=f.text_field :desc, placeholder:"Opis"%>
                <%= f.submit "Prześlij", class:"longbutton",  method: :post %>
            <%end%>
        </div>
        </div>
    </div>
</div>    